import { OtpInputDisplay } from "@/components/common";
import { Button } from "@/components/ui";
import { type ApiResponse, type User } from "@/interfaces";
import { AuthPagesLayout } from "@/layouts";
import { callApi } from "@/lib";
import { useSession } from "@/store";
import { useRouter } from "next/router";
import {
	type Dispatch,
	type FormEvent,
	useEffect,
	useRef,
	useState,
} from "react";
import { toast } from "sonner";

type Props = {
	email?: string;
	loading: boolean;
	otp: string;
	setOtp: Dispatch<React.SetStateAction<string>>;
	handleSubmit: (e: FormEvent<HTMLButtonElement>) => void;
};
const EmailAuth = ({ otp, setOtp, handleSubmit, loading, email }: Props) => {
	const resend = useRef(false);

	const resendCode = async () => {
		// e.preventDefault();
		resend.current = true;
		const { data, error } = await callApi<ApiResponse>("/auth/2fa/code/email");
		if (error) {
			resend.current = false;
			toast.error(error.status, {
				description: error.message,
				duration: 2000,
			});
		} else {
			resend.current = false;
			toast.success("Success", {
				description: (data as { message: string }).message,
				duration: 2000,
			});
		}
	};
	useEffect(() => {
		void resendCode();
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);
	return (
		<OtpInputDisplay
			otp={otp}
			setOtp={setOtp}
			topSection={
				<p className="">{` Enter the 6 digits code we sent to ${email}`}</p>
			}
			bottomSection={
				<>
					<Button
						type="submit"
						disabled={loading}
						loading={loading}
						onClick={(e) => handleSubmit(e)}
						className="my-8 block w-full rounded-md bg-abeg-primary py-4 font-semibold text-white"
						fullWidth
					>
						Confirm
					</Button>
					<div className="space-y-3">
						<p className="text-center">
							Didn&apos;t get a code? We can&nbsp;
							<Button
								type="submit"
								disabled={resend.current}
								onClick={() => void resendCode()}
								className="p-0 font-medium text-abeg-primary disabled:bg-transparent disabled:text-neutral-50"
							>
								resend it
							</Button>
						</p>
						<p className="text-center text-sm">
							If you’re unable to receive a security code, use one of your
							backup codes.
						</p>
					</div>
				</>
			}
		/>
	);
};
const AuthApp = ({ otp, setOtp, handleSubmit, loading }: Props) => {
	return (
		<OtpInputDisplay
			otp={otp}
			setOtp={setOtp}
			topSection={
				<p className="">
					Enter the 6 digits code generated by your authenticator app
				</p>
			}
			bottomSection={
				<Button
					type="submit"
					disabled={loading}
					loading={loading}
					onClick={(e) => handleSubmit(e)}
					className="mt-8 block w-full rounded-md bg-abeg-primary py-4 font-semibold text-white"
					fullWidth
				>
					Confirm
				</Button>
			}
		/>
	);
};
const AuthenticateUser = () => {
	const [otp, setOtp] = useState("");
	const [loading, setLoading] = useState(false);
	const {
		user,
		actions: { updateUser },
	} = useSession((state) => state);
	const router = useRouter();
	const castedUser = user as User;

	const handleSubmit = async (e: React.FormEvent<HTMLButtonElement>) => {
		e.preventDefault();
		if (otp === "")
			return toast.error("Error", {
				description: "Please enter a valid code",
				duration: 1500,
			});
		setLoading(true);
		const { data, error } = await callApi<ApiResponse>("/auth/2fa/verify", {
			token: String(otp),
		});
		if (error) {
			setLoading(false);
			toast.error(error.status, {
				description: error.message,
				duration: 1500,
			});
		} else {
			updateUser(data?.data as User);
			setLoading(false);
			toast.success("Success", {
				description: (data as { message: string }).message,
				duration: 1500,
			});
			router.push("/dashboard");
		}
	};
	return (
		<AuthPagesLayout
			title="Authenticate your Account!"
			content="Enter the 6 digits code sent to your email or generated by your authenticator app."
			withHeader={false}
			hasSuccess={false}
		>
			{castedUser?.twoFA?.type === "EMAIL" ? (
				<EmailAuth
					email={castedUser?.email}
					otp={otp}
					setOtp={setOtp}
					handleSubmit={(e) => void handleSubmit(e)}
					loading={loading}
				/>
			) : (
				<AuthApp
					otp={otp}
					setOtp={setOtp}
					handleSubmit={(e) => void handleSubmit(e)}
					loading={loading}
				/>
			)}
		</AuthPagesLayout>
	);
};

export default AuthenticateUser;
